const wissensbestaende = {
    '5/6': [
    { id: 'w1', titel: 'Schreiben',
      beschreibung: ['Funktion & Form Schreibplan','Strategien der Textüberarbeitung und Fehlerberichtigung', 'einfache Merkmale der Textkohärenz: Satzverknüpfung']},
    { id: 'w2', titel: 'analysierendes Lesen',
      beschreibung: ['Lesetechniken: Nutzung von Hilfsmitteln für organisierende Lesetechniken: Markierungen, Zwischenüberschriften, Kernsatz, Schlüsselbegriffe, Stichwörter'] },
    { id: 'w3', titel: 'Textanalyse',
      beschreibung: ['Merkmale kontinuierlicher und diskontinuierlicher Texte',
        'Funktion und Wirkung ausgewählter sprachkünstlerischer Gestaltungsmittel, z.B. Alliteration, Metapher, Personifikation, Onomatopoesie, Vergleich und Wiederholung',
        'funktionale Bedeutung ausgewählter literarischer Besonderheiten, z.B.: Ort, Zeit, Handlung, Thema, Erzählform (Ich-, Er-/Sie-Erzähler), Aufbau, Figur, Beschreibung literarischer Figuren und Figurenbeziehungen sowie Fiktionssignale → Auswahl → Festlegung?']},
    { id: 'w4', titel: 'Epik',
      beschreibung: ['Märchen (Volks- und Kunstmärchen)','Sage (Heldensage)', 'Fabel', 'Erzählung', 'Gestaltungselemente des lauten (Vor-)lesens'] },
    { id: 'w5', titel: 'Lyrik',
      beschreibung: ['Formmerkmale lyrischer Texte in Funktion und Wirkung: Strophe, Vers, Reim (End-, Haufen-, Paar-, Kreuzreim, umschließender Reim)','Begriffsinhalte: lyrischer Sprecher/ lyrisches Ich und Thema',
        'Rezitation: Betonung, Lautstärke, Sprechtempo, Stimmführung, Körpersprache (Gestik, Mimik und Körperhaltung); Gestaltung von Rezitationen lyrischer Texte']},
    { id: 'w6', titel: 'Textproduktion',
      beschreibung: ['Varianten einfacher textproduktiver Verfahren'] },
    { id: 'w7', titel: 'Rechtschreibung / Grammatik',
      beschreibung: ['Regeln der Interpunktion bei Aufzählung und im zusammengesetzten Satz, wörtliche Rede', 'flektierbarer Wortarten: Substantiv, Verb, Artikel, Adjektiv und Pronomen (Personalpronomen, Possessivpronomen, Demonstrativpronomen, Relativpronomen, Indefinitpronomen)', 'Bildung und Verwendung des Verbs: finite und infinite Formen, Leitformen/Stammformen, (schwache, starke, unregelmäßige Verben), Tempus und Genus verbi', 'unflektierbare Wortarten: Adverb, Präposition, Konjunktion', 'Satzstrukturen: einfacher und zusammengesetzter Satz (Hauptsatz, Nebensatz/Gliedsatz, Gliedteilsatz; Satzreihe/Satzverbindung, Satzgefüge)', 'Satzgliedern: Subjekt, Prädikat (einfaches und mehrgliedriges Prädikat), Objekt (Akkusativ-, Dativ-, Genitiv-, Präpositionalobjekt) und Adverbialbestimmung (Temporal-, Lokal-, Modal-, Kausalbestimmung)',
        'Attribut','Funktion grammatischer Proben: Umstellprobe, Ersatzprobe', 'Satzstruktur: Satzklammer, Feldermodell'] },
    ],
    '7/8': [
    { id: 'w1', titel: 'Sprechen & Zuhören', beschreibung: ['sprachliche Gestaltung der Wiedergabe von Eindrücken, Stimmungen, Gefühlen sowie des Gesamteindrucks (S/Z)']},
    { id: 'w2', titel: 'Argumentation', beschreibung: ['Formen des Argumentierens und Bewertens: Stellungnahme, Streitgespräch, Beurteilung und Schlussfolgerung (S/Z)', 'Merkmale und Verwendung von Behauptung/These, Argument und Beleg/Beispiel (S)', 'Funktionen von verbalen und nonverbalen Mitteln (S/Z)','Formen des Argumentierens und Bewertens: Stellungnahme, Streitgespräch, Beurteilung und Schlussfolgerung (S/Z)', 'Merkmale und Verwendung von Behauptung/These, Argument und Beleg/Beispiel (S)', 'Funktionen von verbalen und nonverbalen Mitteln (S/Z)']},
    { id: 'w3', titel: 'Schreiben', beschreibung: ['Mittel zur Herstellung von Textkohärenz: Ersetzung, Wiederaufnahme (S)',
      'Grundregeln und Formalien des Zitierens (S)',
      'Elemente der Rezeptionssteuerung: Adressatenbezug, Gliederung des Textes und sprachlich-stilistische Gestaltung (T/M)']},
    { id: 'w4', titel: 'Lesen', beschreibung: ['Aspekte und Elemente organisierender Lesetechniken: Textaufbau, strukturmarkierende Hinweise, Text-Mindmap oder Text-Netzwerkkarte, Randnotizen (L)']},
    { id: 'w5', titel: 'pragmatische Texte', beschreibung: ['Merkmale und Funktionen von Sachtexten: Forumsbeitrag? (T/M)', 'Merkmale und Funktionen journalistischer Texte: Ticker, Anzeige, Meldung, Nachricht, Kommentar, Reportage, Interview und Leserbrief, Rezension (T/M)', 'Kriterien der Qualitätsbewertung von Texten: Glaubwürdigkeit der Autorschaft, Medium der Veröffentlichung (T/M)', 'Stilschichten: gehoben, normalsprachlich']},
    { id: 'w6', titel: 'Textanalyse', beschreibung: ['Aufbau und sprachliche Gestaltung der Inhaltsangabe (S)', 'Merkmale der Personencharakteristik, Charakteristik literarischer Figuren (S)', 'Merkmale und Funktionen von Elementen der Texterschließung: Stoff und Motiv (T/M)', 'Funktion und Wirkung sprachkünstlerischer Gestaltungsmittel: Hyperbel, Ellipse, Anapher, rhetorische Frage, Parallelismus, Wortwahl, Sprachklang und Rhythmus (T/M)', 'handschriftliche und digitale Möglichkeiten der Planung, Konzeption, Produktion und Überarbeitung von Texten (S)', 'Aspekte einer Textuntersuchung (S)']},
    { id: 'w7', titel: 'Lyrik', beschreibung: ['gattungstypische Merkmale lyrischer Texte: lyrische Situation, Gestus und lyrisches Bild']},
    { id: 'w7', titel: 'Epik', beschreibung: ['gattungs- und genretypische Merkmale von Kalendergeschichte, Anekdote und Novelle (T/M)', 'Strukturelemente epischer Texte in ihrer funktionalen Bedeutung: Haupt- und Nebenfigur, Komplikationen der Handlungsträger, äußere Handlung und inneres Geschehen, Rahmen und Binnenerzählung, Erzählperspektive (personal, auktorial), Sichtweise des Erzählers (Außensicht, Innensicht) sowie Erzählhaltung (T/M)']},
    { id: 'w7', titel: 'Drama', beschreibung: ['gattungs- und genretypische Merkmale dramatischer Texte: Akt/Aufzug, Szene/Auftritt, Szenenfolge und Nebentext (T/M)', 'Strukturelemente dramatischer Texte in ihren funktionalen Bedeutungen: Thematik, Handlung, Monolog, Dialog, Konflikt und Figurenkonstellation (T/M)']},
    { id: 'w7', titel: 'Rechtschreibung / Grammatik', beschreibung: ['Bildung und Funktion der Modi des Verbs: Indikativ, Konjunktiv I und II sowie Imperativ (SG)'] },
    ],
    '9': [
    { id: 'w1', titel: 'Sprachhandlungen', beschreibung: ['Analysieren und Interpretieren, Erörtern, Referieren (S/Z)'] },
    { id: 'w2', titel: 'textgebundene Erörterung', beschreibung: ['Merkmale einer Diskussion: Diskussionsbeitrag und Diskussionsleitung, Gesprächsphase (S/Z)', 'Aufbau, Struktur und Formen der freien Erörterung: lineare und dialektische Argumentation (S)', 'Strategien der Beeinflussung in Texten (T/M)', 'zwischen Intention und Gestaltung des Textes (T/M)', 'von Texten: Übereinstimmung'] },
    { id: 'w3', titel: 'Bewerbung', beschreibung: ['Merkmale eines Vorstellungsgespräches (S/Z)', 'Formen und Merkmale standardisierter Texte: Lebenslauf und Bewerbung (S)'] },
    { id: 'w4', titel: 'Textanalyse', beschreibung: ['Merkmale von Analyse und Interpretation (S)', 'Regeln der Zitiertechnik (S)', 'Funktion und Wirkung von Wort-, Satz- und Gedankenfiguren: Antithese, Chiasmus, Klimax und Neologismus (T/M)'] },
    { id: 'w5', titel: 'Epik', beschreibung: ['Merkmale und Funktionen der Zeitgestaltung: Zeitdehnung, Zeitdeckung, Zeitraffung; chronologisches und achronologisches Erzählen (T/M)'] },
    { id: 'w6', titel: 'Dramatik', beschreibung: ['Merkmale und Funktionen von Elementen der Texterschließung: Personenverzeichnis, Rollenbiografie, Subtext und Alter-Ego-Technik (T/M)'] },
    { id: 'w7', titel: 'Sprachschulung', beschreibung: ['Stilfärbungen: scherzhaft, vertraulich, ironisch, abwertend und verhüllend (SG)'] },
    ],
    '10': [
    { id: 'w1', titel: 'Redeanalyse', beschreibung: ['Strategien und Techniken des Redeaufbaus (S/Z)', 'Strategien des Argumentierens und Appellierens (S/Z)', 'Funktionen paraverbaler Mittel (S/Z)', 'Sprachhandlungen: Appellieren, Modalisieren, Konzedieren, Positionieren (S/Z)', 'Aspekte der Redeanalyse: Anlass, Redesituation, Argumentationsansatz und Argumentationsstruktur (T/M)'] },
    { id: 'w2', titel: 'textgebundene Erörterung', beschreibung: ['Aufbau, Struktur und Gestaltungsmittel'] },
    { id: 'w3', titel: 'materialgestütztes Schreiben', beschreibung: ['Kriterien der Qualitätsbewertung von Texten: Expertise der Autorschaft, Veröffentlichungskontext (T/M)', 'lexikalische und syntaktische Mittel des Appellierens, Modalisierens, Konzedierens (SG)'] },
    { id: 'w4', titel: 'Formen der Interpretation', beschreibung: ['textimmanent, textextern; linear, aspektorientiert (S)'] },
    { id: 'w5', titel: 'Wort-, Satz- und Gedankenfiguren', beschreibung: ['Allegorie, Akkumulation, Correctio, Euphemismus, Inversion, Ironie,Oxymoron, Paradoxon und Symbol (T/M)'] },
    { id: 'w6', titel: 'Strukturelemente', beschreibung: ['Handlungsverlauf, Figurenkonstellation, Konflikt sowie Konfliktgestaltung (T/M)'] },
    { id: 'w7', titel: 'Werk im Kontext seiner Literaturepoche', beschreibung: [] },
    ],
  };
  export default wissensbestaende;